# -*- coding: utf-8 -*-
"""Agente_gym.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GSfjsgXXz06LOTMgnedMVxpmtl4jwZvQ
"""

# ================================================================
# Agente_gym.py
# FitCoach — Agente de rutinas de gimnasio

import pandas as pd
import re
from pydantic import BaseModel

# ── Cargar CSV ────────────────────────────────────────────────────
df = pd.read_csv("ejercicios.csv")

# Normalizar columnas de texto para evitar errores de mayúsculas/espacios
df["zona"]  = df["zona"].str.lower().str.strip()
df["nivel"] = df["nivel"].str.lower().str.strip()
print(f"CSV cargado: {len(df)} ejercicios | Zonas: {sorted(df['zona'].unique())}")


# ── Modelo de entrada ─────────────────────────────────────────────
class RutinaRequest(BaseModel):
    nivel:   str
    grupos:  list
    tiempo:  int   # minutos totales disponibles


# ================================================================
# HERRAMIENTA 1 — consulta_ejercicios
# Consulta datos locales del CSV (dato estructurado)
# ================================================================
def consulta_ejercicios(grupo: str, nivel: str) -> list | dict:
    """
    Filtra el CSV por zona y nivel.
    Fallback: si no hay ejercicios para ese nivel exacto,
    devuelve todos los de esa zona (sin importar nivel).
    Si la zona no existe, devuelve dict con error y opciones.
    """
    grupo = grupo.lower().strip()
    nivel = nivel.lower().strip()

    # Verificar que la zona existe en el CSV
    zonas_disponibles = sorted(df["zona"].unique())
    if grupo not in zonas_disponibles:
        # Intentar mapear zonas alternativas comunes
        mapa_alternativo = {
            "cardio":   "piernas",   # cardio no está en CSV → redirige a piernas
            "gluteos":  "piernas",
            "lumbar":   "espalda",
            "abdomen":  "core",
            "abs":      "core",
            "brazos":   "biceps",
            "espalda baja": "espalda",
        }
        if grupo in mapa_alternativo:
            grupo = mapa_alternativo[grupo]
            print(f"  ↳ Zona redirigida a: {grupo}")
        else:
            return {
                "error": f"Zona muscular '{grupo}' no encontrada.",
                "opciones": zonas_disponibles
            }

    # Filtro por zona y nivel
    resultado = df[
        (df["zona"] == grupo) &
        (df["nivel"] == nivel)
    ]

    # Fallback: si no hay para ese nivel, tomar todos los de la zona
    if resultado.empty:
        print(f"  ↳ Sin ejercicios para nivel '{nivel}' en '{grupo}'. Usando fallback de zona.")
        resultado = df[df["zona"] == grupo]

    return resultado.to_dict(orient="records")


# ================================================================
# HERRAMIENTA 2 — ajustar_por_tiempo
# Cálculo dinámico: selecciona ejercicios que quepan en el tiempo
# ================================================================
def ajustar_por_tiempo(
    ejercicios: list,
    tiempo: int,
    grupos_con_ejercicios: list
) -> tuple[list, int]:
    """
    Selecciona ejercicios que caben en el tiempo disponible.
    Reparte el tiempo útil (total - 10 min calentamiento) entre
    los grupos que realmente tienen ejercicios disponibles.

    BUG 2 CORREGIDO: duración calculada completamente en minutos.
    BUG 4 CORREGIDO: división solo entre grupos con ejercicios.
    """
    tiempo_util = tiempo - 10  # reservar 10 min para calentamiento

    # Repartir tiempo solo entre grupos que tienen ejercicios (BUG 4)
    n_grupos = len(grupos_con_ejercicios) if grupos_con_ejercicios else 1
    tiempo_por_grupo = tiempo_util / n_grupos

    # Agrupar ejercicios por zona
    ejercicios_por_zona: dict[str, list] = {}
    for ej in ejercicios:
        zona = ej["zona"].lower()
        if zona not in ejercicios_por_zona:
            ejercicios_por_zona[zona] = []
        ejercicios_por_zona[zona].append(ej)

    rutina = []
    tiempo_total = 10  # calentamiento ya incluido

    for zona, lista in ejercicios_por_zona.items():
        acumulado = 0.0
        for ej in lista:
            # duracion_serie_min = minutos de trabajo por serie
            # descanso_seg / 60  = minutos de descanso por serie
            duracion_trabajo  = ej["duracion_serie_min"]
            duracion_descanso = (ej["descanso_seg"] / 60) * ej["series_sugeridas"]
            duracion_total_min = duracion_trabajo + duracion_descanso

            # Solo agregar si cabe en el tiempo asignado a este grupo
            if acumulado + duracion_total_min > tiempo_por_grupo:
                break

            rutina.append({
                "nombre":   ej["nombre"],
                "zona":     zona,
                "series":   ej["series_sugeridas"],
                "reps":     ej["reps_sugeridas"],
                "descanso": ej["descanso_seg"],
                "duracion_min": round(duracion_total_min, 1),
            })
            acumulado      += duracion_total_min
            tiempo_total   += duracion_total_min

    return rutina, round(tiempo_total)


# ================================================================
# HERRAMIENTA 3 — organizar_rutina
# Estructura la salida de forma legible con calentamiento y cierre
# ================================================================
def organizar_rutina(rutina: list) -> list:
    """
    Agrega calentamiento y vuelta a la calma al inicio y fin,
    y numera los ejercicios de forma ordenada.
    """
    salida = []

    # Calentamiento siempre al inicio
    salida.append({
        "ejercicio": "Calentamiento",
        "detalle":   "5 min cardio ligero + 5 min movilidad articular",
        "tiempo":    10,
    })

    # Ejercicios de la rutina
    for i, ej in enumerate(rutina, start=1):
        salida.append({
            "ejercicio": f"Ejercicio {i} — {ej['zona'].capitalize()}",
            "detalle": (
                f"{ej['nombre']}  ·  "
                f"{ej['series']} series × {ej['reps']} reps  ·  "
                f"{ej['descanso']}s descanso"
            ),
            "tiempo": ej["duracion_min"],
        })

    # Vuelta a la calma al final
    salida.append({
        "ejercicio": "Vuelta a la calma",
        "detalle":   "5 min estiramientos estáticos de las zonas trabajadas",
        "tiempo":    5,
    })

    return salida


# ================================================================
# Convierte texto como "1 hora con 45 min" → 105 minutos
# ================================================================
def parse_tiempo(texto: str) -> int:
    """
    Extrae el tiempo en minutos del texto del usuario.
    Soporta: "1 hora", "2 horas", "45 min", "1 hora con 30 min",
             "90 minutos", "1h30", "60".
    Default: 60 minutos si no se detecta nada.
    """
    texto = texto.lower()
    minutos = 0

    # Detectar horas (1 hora, 2 horas, 1h)
    match_horas = re.search(r"(\d+)\s*hora", texto)
    if match_horas:
        minutos += int(match_horas.group(1)) * 60

    # Detectar minutos (45 min, 30 minutos, con 45)
    match_min = re.search(r"(\d+)\s*min", texto)
    if match_min:
        minutos += int(match_min.group(1))

    # Si solo hay un número suelto y no se detectó nada
    if minutos == 0:
        match_solo = re.search(r"\b(\d{2,3})\b", texto)
        if match_solo:
            minutos = int(match_solo.group(1))

    return minutos if minutos > 0 else 60  # default 60 min


# ================================================================
# FUNCIÓN PRINCIPAL — run_agent()
# ================================================================
def run_agent(input_text: str) -> str:
    """
    Procesa el texto libre del usuario y devuelve la rutina
    formateada en tabla Markdown con tiempo total.

    Flujo:
    1. Extrae nivel, grupos musculares y tiempo del texto.
    2. Valida que la solicitud sea de entrenamiento (dominio).
    3. Para cada grupo: consulta ejercicios del CSV (Tool 1).
    4. Ajusta los ejercicios al tiempo disponible (Tool 2).
    5. Organiza la rutina con calentamiento y cierre (Tool 3).
    6. Formatea y devuelve la tabla.
    """
    print(f"\n{'='*60}")
    print(f"Entrada: {input_text}")
    print('='*60)

    # ── Extraer nivel ─────────────────────────────────────────────
    if "principiante" in input_text.lower():
        nivel = "principiante"
    elif "avanzado" in input_text.lower():
        nivel = "avanzado"
    else:
        nivel = "intermedio"  # default si no especifica

    # ── Extraer grupos musculares ──────────────────────────────────
    zonas_conocidas = [
        "espalda", "biceps", "triceps", "pecho",
        "piernas", "hombros", "core", "cardio",
        "gluteos", "abdomen",
    ]
    grupos = []
    for zona in zonas_conocidas:
        if zona in input_text.lower():
            grupos.append(zona)

    tiempo = parse_tiempo(input_text)

    print(f"  Nivel detectado : {nivel}")
    print(f"  Grupos detectados: {grupos}")
    print(f"  Tiempo detectado: {tiempo} minutos")

    # ── Validación de dominio ──────────────────────────────────────
    if not grupos:
        return (
            "⚠️ Este agente solo atiende consultas de rutinas de "
            "entrenamiento físico.\n"
            "Puedes pedirme rutinas para: "
            f"{', '.join(zonas_conocidas)}."
        )

    # Validar tiempo mínimo
    if tiempo < 15:
        return (
            f"⚠️ El tiempo detectado ({tiempo} min) es muy corto "
            "para una rutina útil.\n"
            "Especifica al menos 20 minutos. Ej: 'tengo 30 minutos'."
        )

    req = RutinaRequest(nivel=nivel, grupos=grupos, tiempo=tiempo)

    # ── Tool 1: consultar ejercicios ──────────────────────────────
    print("\n[Tool 1] Consultando ejercicios del CSV...")
    todos_ejercicios = []
    grupos_con_ejercicios = []

    for grupo in req.grupos:
        resultado = consulta_ejercicios(grupo, req.nivel)

        if isinstance(resultado, dict) and "error" in resultado:
            print(f"  ✗ {resultado['error']}")
            continue  # saltar este grupo, no detener todo

        if not resultado:
            print(f"  ✗ Sin ejercicios para '{grupo}'.")
            continue

        print(f"  ✓ {grupo}: {len(resultado)} ejercicios encontrados")
        todos_ejercicios.extend(resultado)
        grupos_con_ejercicios.append(grupo)

    if not todos_ejercicios:
        return (
            "⚠️ No se encontraron ejercicios para los grupos y nivel indicados.\n"
            f"Intenta con: nivel principiante/intermedio/avanzado y zonas: "
            f"{', '.join(sorted(df['zona'].unique()))}."
        )

    # ── Tool 2: ajustar por tiempo ────────────────────────────────
    print(f"\n[Tool 2] Ajustando {len(todos_ejercicios)} ejercicios a {tiempo} min...")
    rutina, tiempo_total = ajustar_por_tiempo(
        todos_ejercicios, req.tiempo, grupos_con_ejercicios
    )
    print(f"  ✓ Ejercicios seleccionados: {len(rutina)} | Tiempo estimado: {tiempo_total} min")

    if not rutina:
        return (
            f"⚠️ El tiempo disponible ({tiempo} min) no es suficiente "
            "para incluir ejercicios.\n"
            "Se necesitan al menos 20 minutos. Aumenta el tiempo disponible."
        )

    # ── Tool 3: organizar rutina ──────────────────────────────────
    print("\n[Tool 3] Organizando rutina final...")
    salida = organizar_rutina(rutina)

    # ── Formatear tabla Markdown ──────────────────────────────────
    tabla  = "| # | Ejercicio | Detalle | Tiempo |\n"
    tabla += "|---|-----------|---------|--------|\n"
    for i, fila in enumerate(salida):
        num = str(i) if i > 0 and i < len(salida) - 1 else "—"
        tabla += (
            f"| {num} | **{fila['ejercicio']}** | "
            f"{fila['detalle']} | "
            f"{fila['tiempo']} min |\n"
        )

    resumen = (
        f"\n⏱ **Tiempo total estimado:** ~{tiempo_total + 5} min "
        f"(incluyendo vuelta a la calma)\n"
        f"💪 **Nivel:** {nivel.capitalize()} | "
        f"**Grupos:** {', '.join(grupos_con_ejercicios).capitalize()}\n"
        f"💡 Rutina ajustada dinámicamente al tiempo disponible."
    )

    return tabla + resumen


# -------------------------------
# Interfaz Streamlit
# -------------------------------
st.title("🏋️ FitCoach - Generador de Rutinas")

nivel = st.selectbox("Nivel de entrenamiento", ["principiante", "intermedio", "avanzado"])
grupos = st.multiselect("Grupos musculares", ["espalda", "biceps", "triceps", "pecho", "piernas", "hombros", "core", "cardio"])
tiempo = st.slider("Tiempo disponible (minutos)", 20, 180, 60)

if st.button("Generar rutina"):
    salida, tiempo_total = run_agent(nivel, grupos, tiempo)
    st.write("### Rutina generada")
    st.table(salida)
    st.write(f"⏱ Tiempo total: ~{tiempo_total} min")
    st.info("💡 Rutina ajustada dinámicamente al tiempo disponible.")

